service: 'openapi-ride'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  stage: stage
  lambdaHashingVersion: '20201221'
  apiGateway:
    shouldStartNameWithService: true

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-webpack-prisma
  - serverless-doppler
  - serverless-offline

custom:
  webpack:
    includeModules: true
    packager: 'yarn'
  serverless-offline:
    noPrependStageInUrl: true

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          method: ANY
          path: '{proxy+}'

  returnedPhotoChecker:
    handler: src/schedulers/returnedPhotoChecker.onReturnedPhotoChecker
    events:
      - schedule:
          enabled: true
          rate: rate(5 minutes)
